-- TOF kamp: namen updaten + nieuwe spelers uit inschrijvingen
-- Veilig te herhalen (UPSERT op id)

INSERT INTO camp_players (id, full_name, nickname, group_id, camp_id) VALUES
  ('camp-p1',  'Arthur Rozemulder', 'Arthur', NULL, 'tof'),
  ('camp-p2',  'Dann Onderdijk', 'Dann', NULL, 'tof'),
  ('camp-p3',  'Mees van Wersch', 'Mees', NULL, 'tof'),
  ('camp-p4',  'Stijn Langendoen', 'Stijn', NULL, 'tof'),
  ('camp-p5',  'Beau van der Reiden', 'Beau', NULL, 'tof'),
  ('camp-p6',  'Enzo Sergio Lobs Tanzarella', 'Enzo L', NULL, 'tof'),
  ('camp-p7',  'Bor de Wolf', 'Bor', NULL, 'tof'),
  ('camp-p8',  'Lars Rijke', 'Lars', NULL, 'tof'),
  ('camp-p9',  'Fayenne Mudde', 'Fayenne', NULL, 'tof'),
  ('camp-p10', 'Juliette Herweijer', 'Juliette', NULL, 'tof'),
  ('camp-p11', 'Flynn Wolterbeek', 'Flynn', NULL, 'tof'),
  ('camp-p12', 'Lukas Langendoen', 'Lukas', NULL, 'tof'),
  ('camp-p13', 'Casper den Haan', 'Casper', NULL, 'tof'),
  ('camp-p14', 'Raymond den Haan', 'Raymond', NULL, 'tof'),
  ('camp-p15', 'Riven Klein', 'Riven', NULL, 'tof'),
  ('camp-p16', 'Chazz Klein', 'Chazz', NULL, 'tof'),
  ('camp-p17', 'Hayden Klein', 'Hayden', NULL, 'tof'),
  ('camp-p18', 'Vinn de Bloeme', 'Vinn', NULL, 'tof'),
  ('camp-p19', 'Kai de Laat', 'Kai', NULL, 'tof'),
  ('camp-p20', 'Lasse de Laat', 'Lasse', NULL, 'tof'),
  ('camp-p21', 'Siem Timmerman', 'Siem', NULL, 'tof'),
  ('camp-p22', 'Celina Van der Veen', 'Celina', NULL, 'tof'),
  ('camp-p23', 'Kayleigh van der Veen', 'Kayleigh', NULL, 'tof'),
  ('camp-p24', 'Enzo Landman', 'Enzo La', NULL, 'tof'),
  ('camp-p25', 'Luc Vos', 'Luc', NULL, 'tof'),
  ('camp-p26', 'Sanne Dikmans', 'Sanne', NULL, 'tof'),
  ('camp-p27', 'Raúl Monfrooij', 'Raúl', NULL, 'tof'),
  ('camp-p28', 'Noa van Lankeren', 'Noa', NULL, 'tof'),
  ('camp-p29', 'Tijn van Wijk', 'Tijn W', NULL, 'tof'),
  ('camp-p30', 'Fay van Bogeriej', 'Fay', NULL, 'tof'),
  ('camp-p31', 'Lou van Bogerijen', 'Lou', NULL, 'tof'),
  ('camp-p32', 'Philou Spuijbroek Kievid', 'Philou', NULL, 'tof'),
  ('camp-p33', 'Olivia Spuijbroek Kievid', 'Olivia S', NULL, 'tof'),
  ('camp-p34', 'Esmee Weeda', 'Esmee', NULL, 'tof'),
  ('camp-p35', 'Niilo Baars', 'Niilo', NULL, 'tof'),
  ('camp-p36', 'Just Baars', 'Just', NULL, 'tof'),
  ('camp-p37', 'Sev Onderdijk', 'Sev', NULL, 'tof'),
  ('camp-p38', 'Jadie Menheere', 'Jadie', NULL, 'tof'),
  ('camp-p39', 'Naud Bal', 'Naud', NULL, 'tof'),
  ('camp-p40', 'Dieuwertje Meijer', 'Dieuwertje', NULL, 'tof'),
  ('camp-p41', 'Puck Wouters', 'Puck', NULL, 'tof'),
  ('camp-p42', 'Floor Kruit', 'Floor K', NULL, 'tof'),
  ('camp-p43', 'Senna Weeda', 'Senna', NULL, 'tof'),
  ('camp-p44', 'Benthe Steenbergen', 'Benthe', NULL, 'tof'),
  ('camp-p45', 'Thijm de Cocq', 'Thijm', NULL, 'tof'),
  ('camp-p46', 'Vince Frentzen', 'Vince', NULL, 'tof'),
  ('camp-p47', 'Julie Frentzen', 'Julie', NULL, 'tof'),
  ('camp-p48', 'Kaelynn Langbroek', 'Kaelynn', NULL, 'tof'),
  ('camp-p49', 'Dede van Nieuwenhoven', 'Dede', NULL, 'tof'),
  ('camp-p50', 'Jits Timmerman', 'Jits', NULL, 'tof'),
  ('camp-p51', 'Marie-Lou Klootwijk', 'Marie-Lou', NULL, 'tof'),
  ('camp-p52', 'Sophie Rozemulder', 'Sophie', NULL, 'tof'),
  ('camp-p53', 'Floris Vinks', 'Floris', NULL, 'tof'),
  ('camp-p54', 'Olivia van den Berg', 'Olivia v', NULL, 'tof'),
  ('camp-p55', 'Valerie van den Berg', 'Valerie', NULL, 'tof'),
  ('camp-p56', 'Lily van der Heijden', 'Lily', NULL, 'tof'),
  ('camp-p57', 'Vere Mol', 'Vere', NULL, 'tof'),
  ('camp-p58', 'Youp Dijkman', 'Youp', NULL, 'tof'),
  ('camp-p59', 'Tijn van Es', 'Tijn E', NULL, 'tof'),
  ('camp-p60', 'Georgina Jones', 'Georgina', NULL, 'tof'),
  ('camp-p61', 'Lewis van den Blink', 'Lewis', NULL, 'tof'),
  ('camp-p62', 'River Cornelius', 'River', NULL, 'tof'),
  ('camp-p63', 'Guusje Bots', 'Guusje', NULL, 'tof'),
  ('camp-p64', 'Sophie van de Kar', 'Sophie v', NULL, 'tof'),
  ('camp-p65', 'Jelte Zwolle', 'Jelte', NULL, 'tof')
ON CONFLICT (id) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  nickname = EXCLUDED.nickname,
  camp_id = EXCLUDED.camp_id;
